import Head from "next/head";
import { Inter } from "next/font/google";
import About from "@/components/About/About";
import Header from "@/components/Shared/Header/Header";
import Products from "@/components/Products/Products";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>To-Leet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Products></Products>
        <About></About>
      </main>
    </>
  );
}
