/* eslint-disable react/no-unescaped-entities */
import React, { useContext } from "react";
import Head from "next/head";
import DestinationType from "@/components/Home/DestinationType/DestinationType";
import PostCounter from "@/components/Home/PostCounter/PostCounter";
import Banner from "@/components/Home/Banner/Banner";
import { StateContext } from "@/Context/StateContext/StateContext";
import style from "../styles/banner.module.css";
import About from "@/components/About/About";

function Home() {
  const { filterTypeCity, filterTypeDivision, isOpen }: any =
    useContext(StateContext);

  return (
    <>
      <Head>
        <title> To-Leet - The Ultimate Rental Solution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link className="rounded-full" rel="icon" href="/favicon.ico" />
      </Head>
      <main
        id={isOpen ? style.modalStyle : ""}
        className={
          filterTypeCity || filterTypeDivision
            ? "bg-primary"
            : "bg-gradient-to-r from-gray-900 via-gray-700 to-gray-900 bg-opacity-70  text-white"
        }
      >
        <Banner></Banner>
        <DestinationType></DestinationType>
        <PostCounter></PostCounter>
        <About></About>
      </main>
    </>
  );
}

export default Home;
